### ISSUE TITLE
The endianness helper function from `util.c` use undefined behaviour

### ISSUE THREAD

**Issue by dr-noid** [VU-Programming/copp-skeleton#14]
The read_uint32_t function uses undefined behaviour which can be catched by `make testsanitizers` when running testadvanced2.

![image](https://github.com/VU-Programming/copp-skeleton/assets/67706284/0878fae9-8e79-4847-9301-dad84cd49423)

By using left shift on the `uint8_t` it gets promoted to a signed int. If we shift so far that the sign bit can get flipped we get undefined behaviour.

I will submit a pull request for a simple fix which first casts to `uint32_t`.

**Comment by atzeus** [comment]
Hi dr-noid! Can you please make your repository private? You are probably unaware, but posting solutions online is not allowed by the exam board. This holds for all VU courses.

**Comment by dr-noid** [comment]
@atzeus Of course I can. I tried to do this when forking the repository but GitHub won't let me mark a forked repository as private. Is there a way to make it private while still keeping the upstream repository, so I can sync any changes?

**Comment by atzeus** [comment]
Thanks! I think if you used the "Use this template" button at the start instead of the "fork" button, then it should be possible to make your "fork" private. I will include this in the instructions.
